# Generated by Django 3.1.6 on 2021-02-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cikkek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255)),
                ('tartalom', models.CharField(max_length=32768)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kepek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kep_hash', models.CharField(max_length=255)),
                ('cikk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.cikkek')),
            ],
        ),
    ]
