# Generated by Django 3.1.6 on 2021-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('felhnev', models.CharField(max_length=255)),
                ('psw', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=11)),
                ('fb', models.CharField(max_length=1024)),
                ('insta', models.CharField(max_length=1024)),
            ],
        ),
    ]
