# Generated by Django 3.1.6 on 2021-02-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='pic_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='blog_app.kepek'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cikkek',
            name='felh_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog_app.admin'),
            preserve_default=False,
        ),
    ]
