# Generated by Django 3.1.6 on 2021-02-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210218_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='pic_id',
        ),
        migrations.CreateModel(
            name='Kepek_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kep_hash', models.CharField(max_length=255)),
                ('felh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.admin')),
            ],
        ),
    ]
