# Generated by Django 3.1.6 on 2021-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20210218_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default='admin@admin.com', max_length=255),
            preserve_default=False,
        ),
    ]
