# Generated by Django 3.1.6 on 2021-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_admin_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cikkek',
            old_name='felh_id',
            new_name='felh',
        ),
        migrations.RenameField(
            model_name='kepek',
            old_name='cikk_id',
            new_name='cikk',
        ),
        migrations.RenameField(
            model_name='kepek_admin',
            old_name='felh_id',
            new_name='felh',
        ),
    ]
