# Generated by Django 3.1.6 on 2021-02-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_admin_kep_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kepek_Admin',
        ),
    ]
